### ISSUE TITLE
IE11 - Grid Support

### ISSUE THREAD

**Issue by designspin** [codebushi/gatsby-starter-forty#10]
Unfortunately the grid implementation does not work in IE11. Any plans on implementing something that could work with Autoprefixers help?

I'm going to switch the grid out for now.

Great work on bringing this template to Gatsby Starters!

**Comment by ramezrafla** [comment]
We had the same issue, turns out the developer implemented his own grid vs the original HTML5UP -- not to mention the latest version of the template uses a new css framework (not SKEL which is deprecated). We already way down the road customizing so in a bind. But you could look into reimporting the original scss and fixing the theme. Then PR it here.

**Comment by ChangoMan** [comment]
Sorry for the delay in response. I had issues with the original SKEL grid, it had some funky css that webpack wasn't able to compile properly. I added the custom grid as a quick-fix. If you want, you can add in another grid, such as https://tailwindcss.com/components/grids
